### ISSUE TITLE
Splitting into smaller libraries?

### ISSUE THREAD

**Issue by greggman** [daffl/launchpad#57]
I was using launchpad to launch a local browser. I upgraded recently because `sys` is deprecated and I was hoping that was fixed. Instead I found that launchpad now uses restify which now uses DTRACE which now makes it incompatible with my usecase.

That got me wondering, why are all these things conflated? I certainly don't need any kind of REST api for launching a browser. I also don't need to launch browserstack or remote browsers. It would be awesome if launchpad was split into some top level API and plugins for the various backends such that a user can install only the parts they need (in my case local browsers only). That would remove tons of dependencies and make it more useful for more people.

**Comment by daffl** [comment]
You are right, I've been meaning to pull out the launchpad server for a while because it really doesn't belong in here.

I'm always a fan of small modules but in this case I am not sure if more modularization than that is really necessary. I usually base the decision off two things: code-base size (which I think in this case with ~500 LOC is manageable) and unnecessary dependencies (which here is potentially only the [Browserstack client](https://github.com/scottgonzalez/node-browserstack) - a very small module with no dependencies on it's own).
